"""
Planner Agent: Decomposes natural language goals into RL training plans.
Uses rule-based parsing with optional LLM integration.
"""
import re
from typing import Dict, List, Optional, Any, Tuple
from dataclasses import dataclass, field
from enum import Enum
import logging


class GameType(Enum):
    """Supported game environments."""
    CARTPOLE = "CartPole-v1"
    FLAPPY_BIRD = "FlappyBird-v0"
    ANGRY_BIRDS = "AngryBird-v0"
    PONG = "Pong-v0"
    BREAKOUT = "Breakout-v0"


class Algorithm(Enum):
    """Supported RL algorithms."""
    PPO = "PPO"
    A2C = "A2C"
    DQN = "DQN"


@dataclass
class TrainingPlan:
    """Structured training plan generated by Planner Agent."""
    goal: str
    target_value: float
    game_type: GameType
    algorithm: Algorithm
    total_timesteps: int
    reward_strategy: str
    success_criteria: str
    constraints: List[str] = field(default_factory=list)
    hyperparameters: Dict[str, Any] = field(default_factory=dict)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict:
        """Convert to dictionary for serialization."""
        return {
            'goal': self.goal,
            'target_value': self.target_value,
            'game_type': self.game_type.value,
            'algorithm': self.algorithm.value,
            'total_timesteps': self.total_timesteps,
            'reward_strategy': self.reward_strategy,
            'success_criteria': self.success_criteria,
            'constraints': self.constraints,
            'hyperparameters': self.hyperparameters,
            'metadata': self.metadata
        }


class PlannerAgent:
    """
    Main planner agent that parses natural language input
    and generates structured RL training plans.
    """

    # Pattern matching rules for common goals
    GOAL_PATTERNS = {
        r'\b(?:maximize|high|best)\s+(?:score|reward)\b': ('maximize_score', 'max_reward'),
        r'\b(?:reach|achieve|get)\s+(?:score|target)\s+of\s+(\d+)': ('target_score', 'target_value'),
        r'\b(?:stay\s+)?alive\s+(?:for|through)\s+(\d+)\s*(?:steps|frames?|seconds?)': ('survive', 'duration'),
        r'\b(?:learn\s+to)\s+move\s+(?:right|left|up|down)': ('learn_movement', 'movement'),
        r'\b(?:balance)\b': ('balance', 'balance'),
        r'\b(?:land)\b': ('land', 'landing')
    }

    ENVIRONMENT_PATTERNS = {
        r'\b(?:cartpole|pole|balancing)\b': GameType.CARTPOLE,
        r'\b(?:flappy|bird|flap)\b': GameType.FLAPPY_BIRD,
        r'\b(?:pong)\b': GameType.PONG,
        r'\b(?:breakout|brick|break)\b': GameType.BREAKOUT,
        r'\b(?:angry|angri)\b': GameType.ANGRY_BIRDS,
    }

    ALGORITHM_PATTERNS = {
        r'\b(?:ppo|proximal)\b': Algorithm.PPO,
        r'\b(?:a2c|advantage)\b': Algorithm.A2C,
        r'\b(?:dqn|deep\s+q)\b': Algorithm.DQN
    }

    def __init__(self, memory_system=None):
        self.memory = memory_system
        self.logger = logging.getLogger(__name__)
        try:
            from langchain_community.llms import Ollama
            self.llm = Ollama(model="llama3", temperature=0.1)
            self.llm_available = True
        except:
            self.llm = None
            self.llm_available = False
            self.logger.warning("Ollama LLM not available - using rule-based fallback")

    def parse_goal(self, user_input: str) -> TrainingPlan:
        """
        Parse natural language input and generate a training plan.

        Args:
            user_input: Natural language description of the goal

        Returns:
            TrainingPlan object with structured parameters
        """
        user_input = user_input.lower().strip()
        if not user_input:
            raise ValueError("Empty user input")

        # Extract game type
        game_type = self._detect_environment(user_input)

        # Extract algorithm preference (default to PPO)
        algorithm = self._detect_algorithm(user_input)

        # Extract goal parameters
        goal_type, target = self._extract_goal_parameters(user_input, game_type)

        # Determine reward strategy
        reward_strategy = self._design_reward_strategy(goal_type, game_type)

        # Determine success criteria
        success_criteria = self._design_success_criteria(goal_type, target, game_type)

        # Estimate timesteps based on complexity
        total_timesteps = self._estimate_timesteps(game_type, goal_type)

        # Configure hyperparameters
        hyperparameters = self._get_hyperparameters(algorithm, game_type)

        # Build constraints list
        constraints = self._extract_constraints(user_input)

        # Create training plan
        plan = TrainingPlan(
            goal=goal_type,
            target_value=target,
            game_type=game_type,
            algorithm=algorithm,
            total_timesteps=total_timesteps,
            reward_strategy=reward_strategy,
            success_criteria=success_criteria,
            constraints=constraints,
            hyperparameters=hyperparameters,
            metadata={
                'raw_input': user_input,
                'parsed_at': self._get_timestamp(),
                'planner_version': '1.0'
            }
        )

        # Store in memory if available
        if self.memory:
            self.memory.save_plan(
                workflow_id="parsed_" + str(hash(user_input))[:8],
                user_input=user_input,
                plan=plan.to_dict(),
                environment=plan.game_type.value,
                algorithm=plan.algorithm.value,
                target_score=plan.target_value,
                metrics=None,
                success=False
            )

        return plan

    def _detect_environment(self, text: str) -> GameType:
        """Detect which game/environment to use."""
        for pattern, env_type in self.ENVIRONMENT_PATTERNS.items():
            if re.search(pattern, text):
                return env_type
        # Default fallback
        return GameType.CARTPOLE

    def _detect_algorithm(self, text: str) -> Algorithm:
        """Detect preferred RL algorithm."""
        for pattern, algo in self.ALGORITHM_PATTERNS.items():
            if re.search(pattern, text):
                return algo
        return Algorithm.PPO  # Default

    def _extract_goal_parameters(self, text: str, game_type: GameType) -> Tuple[str, float]:
        """Extract goal type and target value."""
        # Check for specific numeric targets
        for pattern, (goal_type, param) in self.GOAL_PATTERNS.items():
            match = re.search(pattern, text)
            if match:
                if param == 'target_value' and match.lastindex:
                    return goal_type, float(match.group(1))
                elif param == 'duration' and match.lastindex:
                    return goal_type, float(match.group(1))
                elif param == 'movement':
                    return goal_type, 0.5  # threshold for movement
                else:
                    return goal_type, self._get_default_target(goal_type, game_type)

        # Game-specific defaults
        if game_type == GameType.CARTPOLE:
            return 'balance', 195.0  # CartPole typical target
        elif game_type == GameType.FLAPPY_BIRD:
            return 'maximize_score', 50.0  # Flappy Bird score target
        else:
            return 'maximize_reward', 100.0

    def _get_default_target(self, goal_type: str, game_type: GameType) -> float:
        """Get sensible default target for goal type."""
        defaults = {
            'maximize_score': 100.0,
            'target_score': 50.0,
            'survive': 1000.0,
            'balance': 195.0,
            'land': 10.0
        }
        return defaults.get(goal_type, 100.0)

    def _design_reward_strategy(self, goal_type: str, game_type: GameType) -> str:
        """Design reward function based on goal and environment."""
        strategies = {
            'balance': 'step_reward + termination_penalty',
            'maximize_score': 'score_based + survival_bonus',
            'target_score': 'score_based + milestone_rewards',
            'survive': 'time_survived + distance_traveled',
            'learn_movement': 'action_success + exploration_bonus'
        }
        return strategies.get(goal_type, 'default_reward')

    def _design_success_criteria(self, goal_type: str, target: float, game_type: GameType) -> str:
        """Define when the goal is considered achieved."""
        if goal_type in ['maximize_score', 'target_score']:
            return f"Achieve average score >= {target} over 100 consecutive episodes"
        elif goal_type == 'balance':
            return f"Maintain pole upright for >= {target} steps average"
        elif goal_type == 'survive':
            return f"Survive for >= {target} timesteps average"
        else:
            return f"Mean reward >= {target} over evaluation episodes"

    def _estimate_timesteps(self, game_type: GameType, goal_type: str) -> int:
        """Estimate required training timesteps."""
        base_timesteps = {
            GameType.CARTPOLE: 50000,
            GameType.FLAPPY_BIRD: 200000,
            GameType.ANGRY_BIRDS: 300000,  # More complex physics
            GameType.PONG: 500000,
            GameType.BREAKOUT: 300000
        }

        # Adjust based on goal difficulty
        difficulty_multiplier = {
            'balance': 1.0,
            'maximize_score': 2.0,
            'target_score': 1.5,
            'survive': 1.2,
            'learn_movement': 2.5
        }

        base = base_timesteps.get(game_type, 100000)
        mult = difficulty_multiplier.get(goal_type, 1.0)

        return int(base * mult)

    def _get_hyperparameters(self, algorithm: Algorithm, game_type: GameType) -> Dict[str, Any]:
        """Get tuned hyperparameters for algorithm and environment."""
        # These are sensible defaults based on common RL benchmarks
        hyperparams = {
            'PPO': {
                'learning_rate': 3e-4,
                'n_steps': 2048,
                'batch_size': 64,
                'n_epochs': 10,
                'gamma': 0.99,
                'gae_lambda': 0.95,
                'clip_range': 0.2
            },
            'A2C': {
                'learning_rate': 7e-4,
                'n_steps': 5,
                'gamma': 0.99
            },
            'DQN': {
                'learning_rate': 1e-3,
                'buffer_size': 50000,
                'learning_starts': 1000,
                'batch_size': 32,
                'gamma': 0.99
            }
        }

        params = hyperparams.get(algorithm.value, {}).copy()

        # Environment-specific tuning
        if game_type in [GameType.FLAPPY_BIRD, GameType.ANGRY_BIRDS]:
            params['learning_rate'] = 1e-3
            if algorithm == Algorithm.PPO:
                params['n_steps'] = 1024

        return params

    def _extract_constraints(self, text: str) -> List[str]:
        """Extract constraints from user input."""
        constraints = []

        # Time constraints
        if re.search(r'\b(?:quick|fast|fastest)\b', text):
            constraints.append("minimize_training_time")

        # Resource constraints
        if re.search(r'\b(?:lightweight|low\s+memory|small)\b', text):
            constraints.append("limit_memory_usage")

        # Safety constraints
        if re.search(r'\b(?:safe|stable|reliable)\b', text):
            constraints.append("prioritize_stability")

        return constraints

    def _get_timestamp(self) -> str:
        """Get current timestamp."""
        from datetime import datetime
        return datetime.now().isoformat()

    def refine_plan(self, plan: TrainingPlan, feedback: Dict[str, Any]) -> TrainingPlan:
        """Refine plan based on feedback from previous runs."""
        # Adjust hyperparameters based on performance
        if 'low_reward' in feedback.get('issues', []):
            plan.hyperparameters['learning_rate'] *= 1.5
            plan.total_timesteps = int(plan.total_timesteps * 1.5)

        if 'slow_convergence' in feedback.get('issues', []):
            plan.hyperparameters['learning_rate'] *= 2.0

        plan.metadata['refinements'] = plan.metadata.get('refinements', 0) + 1
        return plan

    def suggest_alternatives(self, plan: TrainingPlan) -> List[TrainingPlan]:
        """Generate alternative plans for exploration."""
        alternatives = []

        # Alternative algorithm
        for algo in [Algorithm.A2C, Algorithm.DQN]:
            if algo != plan.algorithm:
                alt = TrainingPlan(
                    goal=plan.goal,
                    target_value=plan.target_value,
                    game_type=plan.game_type,
                    algorithm=algo,
                    total_timesteps=plan.total_timesteps,
                    reward_strategy=plan.reward_strategy,
                    success_criteria=plan.success_criteria,
                    constraints=plan.constraints,
                    hyperparameters=self._get_hyperparameters(algo, plan.game_type),
                    metadata={'alternative_of': plan.to_dict()}
                )
                alternatives.append(alt)

        return alternatives
